apiVersion: v2
name: user-service
description: gRPC User Service for Taskboard
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - grpc
  - microservice
  - authentication
  - users

maintainers:
  - name: Paul Ohrt
    email: paul.ohrt@me.com
